### ISSUE TITLE
This is DDoS

### ISSUE THREAD

**Issue by TO-W** [binsky08/HISinOne-QIS-exam-notification#4]
Running this at the same time on all devices (*/30 * * * *) will cause DDoS all 30 minutes. You might get into trouble with German justice.

**Comment by binsky08** [comment]
hmm, good point
I didn't think it was a problem as this is just an example with */30, but I will change that in the README

**Comment by TO-W** [comment]
It doesn't matter whether you run this once an hour or once a day. You must ensure it is not running at the same time. Otherwise you have DDoS and will get into big trouble.

**Comment by binsky08** [comment]
I tried to prevent it by changing the cronjob examples [df136c5](https://github.com/binsky08/HISinOne-QIS-exam-notification/commit/df136c5c5216a779fcd5d1eec91eee5d454194ff)

**Comment by TO-W** [comment]
I would recommend sleeping a random amount of seconds in the python code (I didn't check whether you already do that), as I guess, most people will use 0 as the minute of the cronjob.

**Comment by binsky08** [comment]
> I would recommend sleeping a random amount of seconds in the python code (I didn't check whether you already do that), as I guess, most people will use 0 as the minute of the cronjob.

I don't think that this would be a good solution.
I changed the defaults in the README and use a random minutes value in the default crontab for the docker container.
